# Generated by Django 4.2.4 on 2023-09-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
